const EMOJIS = [
  // 動物・哺乳類
  { emoji: '🐶', name: '犬', category: '動物' },
  { emoji: '🐱', name: '猫', category: '動物' },
  { emoji: '🐭', name: 'ネズミ', category: '動物' },
  { emoji: '🐹', name: 'ハムスター', category: '動物' },
  { emoji: '🐰', name: 'ウサギ', category: '動物' },
  { emoji: '🦊', name: 'キツネ', category: '動物' },
  { emoji: '🦝', name: 'アライグマ', category: '動物' },
  { emoji: '🐻', name: 'クマ', category: '動物' },
  { emoji: '🐼', name: 'パンダ', category: '動物' },
  { emoji: '🐨', name: 'コアラ', category: '動物' },
  { emoji: '🐯', name: 'トラ', category: '動物' },
  { emoji: '🦁', name: 'ライオン', category: '動物' },
  { emoji: '🐄', name: 'ウシ', category: '動物' },
  { emoji: '🐷', name: 'ブタ', category: '動物' },
  { emoji: '🐑', name: 'ヒツジ', category: '動物' },
  { emoji: '🐐', name: 'ヤギ', category: '動物' },
  { emoji: '🐪', name: 'ラクダ', category: '動物' },
  { emoji: '🦒', name: 'キリン', category: '動物' },
  { emoji: '🐘', name: 'ゾウ', category: '動物' },
  { emoji: '🦏', name: 'サイ', category: '動物' },
  { emoji: '🦛', name: 'カバ', category: '動物' },
  { emoji: '🐴', name: 'ウマ', category: '動物' },
  { emoji: '🐒', name: 'サル', category: '動物' },
  { emoji: '🦍', name: 'ゴリラ', category: '動物' },
  { emoji: '🐋', name: 'クジラ', category: '動物' },
  { emoji: '🐬', name: 'イルカ', category: '動物' },
  { emoji: '🦦', name: 'カワウソ', category: '動物' },
  { emoji: '🦇', name: 'コウモリ', category: '動物' },
  { emoji: '🦨', name: 'スカンク', category: '動物' },
  { emoji: '🦘', name: 'カンガルー', category: '動物' },
  { emoji: '🐿️', name: 'リス', category: '動物' },
  { emoji: '🦔', name: 'ハリネズミ', category: '動物' },
  // 動物・鳥類
  { emoji: '🐔', name: 'ニワトリ', category: '動物' },
  { emoji: '🐧', name: 'ペンギン', category: '動物' },
  { emoji: '🐦', name: '青い鳥', category: '動物' },
  { emoji: '🦉', name: 'フクロウ', category: '動物' },
  { emoji: '🦅', name: 'ワシ', category: '動物' },
  { emoji: '🦆', name: 'アヒル', category: '動物' },
  { emoji: '🦩', name: 'フラミンゴ', category: '動物' },
  { emoji: '🦚', name: 'クジャク', category: '動物' },
  { emoji: '🦜', name: 'オウム', category: '動物' },
  { emoji: '🦢', name: '白鳥', category: '動物' },
  { emoji: '🦄', name: 'ユニコーン', category: '動物' },
  // 動物・爬虫類・両生類
  { emoji: '🐍', name: 'ヘビ', category: '動物' },
  { emoji: '🦎', name: 'トカゲ', category: '動物' },
  { emoji: '🐊', name: 'ワニ', category: '動物' },
  { emoji: '🐢', name: 'カメ', category: '動物' },
  { emoji: '🐸', name: 'カエル', category: '動物' },
  { emoji: '🐉', name: 'ドラゴン', category: '動物' },
  // 動物・魚・海洋生物
  { emoji: '🐟', name: '魚', category: '動物' },
  { emoji: '🐡', name: 'フグ', category: '動物' },
  { emoji: '🦈', name: 'サメ', category: '動物' },
  { emoji: '🐙', name: 'タコ', category: '動物' },
  { emoji: '🦀', name: 'カニ', category: '動物' },
  { emoji: '🦐', name: 'エビ', category: '動物' },
  { emoji: '🐌', name: 'カタツムリ', category: '動物' },
  // 動物・昆虫
  { emoji: '🦋', name: 'チョウ', category: '動物' },
  { emoji: '🐛', name: '毛虫', category: '動物' },
  { emoji: '🐜', name: 'アリ', category: '動物' },
  { emoji: '🐝', name: 'ハチ', category: '動物' },
  { emoji: '🐞', name: 'テントウムシ', category: '動物' },
  { emoji: '🦗', name: 'バッタ', category: '動物' },
  { emoji: '🕷️', name: 'クモ', category: '動物' },
  { emoji: '🦂', name: 'サソリ', category: '動物' },
  // 恐竜・伝説
  { emoji: '🦕', name: '恐竜（長首）', category: '動物' },
  { emoji: '🦖', name: '恐竜（肉食）', category: '動物' },
  // 植物・木
  { emoji: '🌲', name: 'もみの木', category: '植物' },
  { emoji: '🌳', name: '落葉樹', category: '植物' },
  { emoji: '🌴', name: 'ヤシの木', category: '植物' },
  { emoji: '🌵', name: 'サボテン', category: '植物' },
  { emoji: '🌾', name: '稲穂', category: '植物' },
  { emoji: '🍀', name: '四つ葉のクローバー', category: '植物' },
  { emoji: '🍃', name: '葉っぱ', category: '植物' },
  { emoji: '🍁', name: '落ち葉', category: '植物' },
  // 花
  { emoji: '🌹', name: 'バラ', category: '植物' },
  { emoji: '💐', name: '花束', category: '植物' },
  { emoji: '🌻', name: 'ヒマワリ', category: '植物' },
  { emoji: '🌷', name: 'チューリップ', category: '植物' },
  { emoji: '🌸', name: '桜', category: '植物' },
  { emoji: '🌼', name: 'タンポポ', category: '植物' },
  // 果物
  { emoji: '🍎', name: 'リンゴ', category: '果物' },
  { emoji: '🍊', name: 'オレンジ', category: '果物' },
  { emoji: '🍋', name: 'レモン', category: '果物' },
  { emoji: '🍌', name: 'バナナ', category: '果物' },
  { emoji: '🍉', name: 'スイカ', category: '果物' },
  { emoji: '🍇', name: 'ブドウ', category: '果物' },
  { emoji: '🍓', name: 'イチゴ', category: '果物' },
  { emoji: '🍈', name: 'メロン', category: '果物' },
  { emoji: '🍒', name: 'サクランボ', category: '果物' },
  { emoji: '🍑', name: 'モモ', category: '果物' },
  { emoji: '🍍', name: 'パイナップル', category: '果物' },
  { emoji: '🥝', name: 'キウイ', category: '果物' },
  // 野菜
  { emoji: '🍅', name: 'トマト', category: '野菜' },
  { emoji: '🍆', name: 'ナス', category: '野菜' },
  { emoji: '🥦', name: 'ブロッコリー', category: '野菜' },
  { emoji: '🥬', name: 'レタス', category: '野菜' },
  { emoji: '🥒', name: 'キュウリ', category: '野菜' },
  { emoji: '🌽', name: 'トウモロコシ', category: '野菜' },
  { emoji: '🌶️', name: 'トウガラシ', category: '野菜' },
  { emoji: '🥕', name: 'ニンジン', category: '野菜' },
  { emoji: '🧄', name: 'ニンニク', category: '野菜' },
  { emoji: '🧅', name: 'タマネギ', category: '野菜' },
  { emoji: '🥔', name: 'ジャガイモ', category: '野菜' },
  { emoji: '🍠', name: 'サツマイモ', category: '野菜' },
  { emoji: '🌰', name: '栗', category: '野菜' },
  { emoji: '🍄', name: 'キノコ', category: '野菜' },
  // 料理・パン
  { emoji: '🍞', name: 'パン', category: '料理' },
  { emoji: '🥞', name: 'パンケーキ', category: '料理' },
  // 料理・肉・卵
  { emoji: '🍖', name: '骨付き肉', category: '料理' },
  { emoji: '🍗', name: 'チキン', category: '料理' },
  { emoji: '🥓', name: 'ベーコン', category: '料理' },
  { emoji: '🍔', name: 'ハンバーガー', category: '料理' },
  { emoji: '🌭', name: 'ホットドッグ', category: '料理' },
  { emoji: '🍳', name: '目玉焼き', category: '料理' },
  { emoji: '🧀', name: 'チーズ', category: '料理' },
  { emoji: '🥪', name: 'サンドイッチ', category: '料理' },
  // 料理・和食
  { emoji: '🍙', name: 'おにぎり', category: '料理' },
  { emoji: '🍱', name: 'お弁当', category: '料理' },
  { emoji: '🍣', name: '寿司', category: '料理' },
  { emoji: '🍜', name: 'ラーメン', category: '料理' },
  { emoji: '🥟', name: '餃子', category: '料理' },
  { emoji: '🍤', name: '天ぷら', category: '料理' },
  { emoji: '🍢', name: 'おでん', category: '料理' },
  { emoji: '🍛', name: 'カレー', category: '料理' },
  { emoji: '🍚', name: 'ご飯', category: '料理' },
  // 料理・洋食
  { emoji: '🍕', name: 'ピザ', category: '料理' },
  { emoji: '🥗', name: 'サラダ', category: '料理' },
  { emoji: '🍟', name: 'フライドポテト', category: '料理' },
  { emoji: '🍲', name: '鍋', category: '料理' },
  // スイーツ
  { emoji: '🍰', name: 'ショートケーキ', category: 'スイーツ' },
  { emoji: '🍫', name: 'チョコレート', category: 'スイーツ' },
  { emoji: '🍬', name: 'キャンディ', category: 'スイーツ' },
  { emoji: '🍦', name: 'アイスクリーム', category: 'スイーツ' },
  { emoji: '🍩', name: 'ドーナツ', category: 'スイーツ' },
  { emoji: '🍪', name: 'クッキー', category: 'スイーツ' },
  { emoji: '🍯', name: '蜂蜜', category: 'スイーツ' },
  // 飲み物
  { emoji: '☕', name: 'コーヒー', category: '飲み物' },
  { emoji: '🍵', name: 'お茶', category: '飲み物' },
  { emoji: '🍺', name: 'ビール', category: '飲み物' },
  { emoji: '🍷', name: 'ワイン', category: '飲み物' },
  { emoji: '🧃', name: 'ジュース', category: '飲み物' },
  { emoji: '🥛', name: '牛乳', category: '飲み物' },
  // 道具・文房具
  { emoji: '✏️', name: '鉛筆', category: '道具' },
  { emoji: '✂️', name: 'はさみ', category: '道具' },
  { emoji: '📏', name: '定規', category: '道具' },
  { emoji: '📌', name: '画鋲', category: '道具' },
  { emoji: '🔍', name: '虫眼鏡', category: '道具' },
  // 道具・工具
  { emoji: '🔨', name: 'ハンマー', category: '道具' },
  { emoji: '🔧', name: 'レンチ', category: '道具' },
  { emoji: '⛏️', name: 'つるはし', category: '道具' },
  { emoji: '🔑', name: '鍵', category: '道具' },
  // 道具・医療
  { emoji: '💉', name: '注射器', category: '道具' },
  { emoji: '💊', name: '薬', category: '道具' },
  { emoji: '🔬', name: '顕微鏡', category: '道具' },
  { emoji: '🧪', name: '試験管', category: '道具' },
  // 武器
  { emoji: '⚔️', name: '剣', category: '武器' },
  { emoji: '🛡️', name: '盾', category: '武器' },
  { emoji: '🏹', name: '弓矢', category: '武器' },
  { emoji: '🔫', name: '銃', category: '武器' },
  { emoji: '💣', name: '爆弾', category: '武器' },
  { emoji: '🪓', name: '斧', category: '武器' },
  { emoji: '🪃', name: 'ブーメラン', category: '武器' },
  // 日用品
  { emoji: '💡', name: '電球', category: '道具' },
  { emoji: '🕯️', name: 'ろうそく', category: '道具' },
  // 楽器・音楽
  { emoji: '🎸', name: 'ギター', category: '音楽' },
  { emoji: '🎻', name: 'バイオリン', category: '音楽' },
  { emoji: '🎹', name: 'ピアノ', category: '音楽' },
  { emoji: '🎺', name: 'トランペット', category: '音楽' },
  { emoji: '🥁', name: 'ドラム', category: '音楽' },
  { emoji: '🎤', name: 'マイク', category: '音楽' },
  { emoji: '🎵', name: '音符', category: '音楽' },
  { emoji: '📻', name: 'ラジオ', category: '音楽' },
  // スポーツ用具
  { emoji: '⚽', name: 'サッカーボール', category: 'スポーツ' },
  { emoji: '⚾', name: '野球ボール', category: 'スポーツ' },
  { emoji: '🏀', name: 'バスケットボール', category: 'スポーツ' },
  { emoji: '🎾', name: 'テニスラケット', category: 'スポーツ' },
  { emoji: '🏐', name: 'バレーボール', category: 'スポーツ' },
  { emoji: '🏉', name: 'ラグビーボール', category: 'スポーツ' },
  { emoji: '🏓', name: '卓球', category: 'スポーツ' },
  { emoji: '🏸', name: 'バドミントン', category: 'スポーツ' },
  { emoji: '⛳', name: 'ゴルフ', category: 'スポーツ' },
  { emoji: '🥊', name: 'ボクシンググローブ', category: 'スポーツ' },
  { emoji: '🥋', name: '柔道着', category: 'スポーツ' },
  { emoji: '🎣', name: '釣り竿', category: 'スポーツ' },
  { emoji: '⛸️', name: 'スケート靴', category: 'スポーツ' },
  { emoji: '🏆', name: 'トロフィー', category: 'スポーツ' },
  { emoji: '🥇', name: '金メダル', category: 'スポーツ' },
  { emoji: '🏋️', name: '重量挙げ', category: 'スポーツ' },
  // 乗り物・陸
  { emoji: '🚗', name: '車', category: '乗り物' },
  { emoji: '🚚', name: 'トラック', category: '乗り物' },
  { emoji: '🚲', name: '自転車', category: '乗り物' },
  { emoji: '🏍️', name: 'バイク', category: '乗り物' },
  { emoji: '🚃', name: '電車', category: '乗り物' },
  { emoji: '🚅', name: '新幹線', category: '乗り物' },
  { emoji: '🚜', name: 'トラクター', category: '乗り物' },
  // 乗り物・空
  { emoji: '✈️', name: '飛行機', category: '乗り物' },
  { emoji: '🚀', name: 'ロケット', category: '乗り物' },
  { emoji: '🚁', name: 'ヘリコプター', category: '乗り物' },
  { emoji: '🛸', name: 'UFO', category: '乗り物' },
  // 乗り物・海
  { emoji: '🚢', name: '船', category: '乗り物' },
  { emoji: '⚓', name: 'いかり', category: '乗り物' },
  // 建物
  { emoji: '⛩️', name: '神社', category: '建物' },
  { emoji: '🏯', name: '城（日本）', category: '建物' },
  { emoji: '🏠', name: '家', category: '建物' },
  { emoji: '🏰', name: '城（西洋）', category: '建物' },
  { emoji: '⛪', name: '教会', category: '建物' },
  // 自然・場所
  { emoji: '🌋', name: '火山', category: '自然' },
  { emoji: '🏜️', name: '砂漠', category: '自然' },
  { emoji: '🏖️', name: 'ビーチ', category: '自然' },
  { emoji: '🏝️', name: '島', category: '自然' },
  { emoji: '🌉', name: '橋', category: '自然' },
  { emoji: '🏙️', name: '都会', category: '自然' },
  // 人・職業
  { emoji: '👮', name: '警察官', category: '人' },
  { emoji: '🕵️', name: '探偵', category: '人' },
  { emoji: '🤴', name: '王子', category: '人' },
  { emoji: '👸', name: '王女', category: '人' },
  { emoji: '👼', name: '天使', category: '人' },
  { emoji: '🎅', name: 'サンタ', category: '人' },
  { emoji: '🧙', name: '魔法使い', category: '人' },
  { emoji: '🧟', name: 'ゾンビ', category: '人' },
  { emoji: '🤖', name: 'ロボット', category: '人' },
  { emoji: '🧛', name: '吸血鬼', category: '人' },
  { emoji: '🧜', name: '人魚', category: '人' },
  { emoji: '🧚', name: '妖精', category: '人' },
  { emoji: '👨‍⚕️', name: '医者', category: '人' },
  { emoji: '👑', name: '王冠', category: '人' },
  { emoji: '💪', name: '筋肉', category: '人' },
  { emoji: '🤝', name: '握手', category: '人' },
  { emoji: '🙏', name: '祈る手', category: '人' },
  // 国旗
  { emoji: '🇯🇵', name: '日本', category: '国旗' },
  { emoji: '🇺🇸', name: 'アメリカ', category: '国旗' },
  { emoji: '🇬🇧', name: 'イギリス', category: '国旗' },
  { emoji: '🇫🇷', name: 'フランス', category: '国旗' },
  { emoji: '🇩🇪', name: 'ドイツ', category: '国旗' },
  { emoji: '🇮🇹', name: 'イタリア', category: '国旗' },
  { emoji: '🇪🇸', name: 'スペイン', category: '国旗' },
  { emoji: '🇨🇳', name: '中国', category: '国旗' },
  { emoji: '🇰🇷', name: '韓国', category: '国旗' },
  { emoji: '🇷🇺', name: 'ロシア', category: '国旗' },
  { emoji: '🇧🇷', name: 'ブラジル', category: '国旗' },
  { emoji: '🇦🇺', name: 'オーストラリア', category: '国旗' },
  { emoji: '🇨🇦', name: 'カナダ', category: '国旗' },
  { emoji: '🇮🇳', name: 'インド', category: '国旗' },
  { emoji: '🇲🇽', name: 'メキシコ', category: '国旗' },
  { emoji: '🇹🇭', name: 'タイ', category: '国旗' },
  { emoji: '🇬🇷', name: 'ギリシャ', category: '国旗' },
  { emoji: '🇹🇼', name: '台湾', category: '国旗' },
  // 天気
  { emoji: '☀️', name: '晴れ', category: '天気' },
  { emoji: '☁️', name: '曇り', category: '天気' },
  { emoji: '❄️', name: '雪', category: '天気' },
  { emoji: '⚡', name: '雷', category: '天気' },
  { emoji: '🌈', name: '虹', category: '天気' },
  { emoji: '🌪️', name: '竜巻', category: '天気' },
  { emoji: '🌀', name: '台風', category: '天気' },
  { emoji: '⛄', name: '雪だるま', category: '天気' },
  // 天体・宇宙
  { emoji: '🌙', name: '三日月', category: '天体' },
  { emoji: '⭐', name: '星', category: '天体' },
  { emoji: '🌠', name: '流れ星', category: '天体' },
  { emoji: '🌍', name: '地球', category: '天体' },
  { emoji: '☄️', name: '彗星', category: '天体' },
  { emoji: '🌌', name: '銀河', category: '天体' },
  // PC・通信
  { emoji: '💻', name: 'パソコン', category: 'テクノロジー' },
  { emoji: '📱', name: 'スマホ', category: 'テクノロジー' },
  { emoji: '📺', name: 'テレビ', category: 'テクノロジー' },
  { emoji: '📷', name: 'カメラ', category: 'テクノロジー' },
  { emoji: '🔋', name: 'バッテリー', category: 'テクノロジー' },
  // 文書・本
  { emoji: '✉️', name: '手紙', category: 'テクノロジー' },
  { emoji: '📦', name: '小包', category: 'テクノロジー' },
  { emoji: '📚', name: '本', category: 'テクノロジー' },
  { emoji: '📰', name: '新聞', category: 'テクノロジー' },
  { emoji: '🗺️', name: '地図', category: 'テクノロジー' },
  { emoji: '📅', name: 'カレンダー', category: 'テクノロジー' },
  // お金・宝
  { emoji: '💵', name: 'お札', category: '宝' },
  { emoji: '💎', name: '宝石', category: '宝' },
  { emoji: '💍', name: '指輪', category: '宝' },
  { emoji: '👛', name: '財布', category: '宝' },
  // ファッション
  { emoji: '🎩', name: '帽子', category: 'ファッション' },
  { emoji: '👓', name: '眼鏡', category: 'ファッション' },
  { emoji: '🕶️', name: 'サングラス', category: 'ファッション' },
  { emoji: '👟', name: '靴', category: 'ファッション' },
  { emoji: '👠', name: 'ハイヒール', category: 'ファッション' },
  { emoji: '☂️', name: '傘', category: 'ファッション' },
  { emoji: '⌚', name: '時計', category: 'ファッション' },
  // 遊び・エンタメ
  { emoji: '🃏', name: 'トランプ', category: 'エンタメ' },
  { emoji: '♟️', name: 'チェス', category: 'エンタメ' },
  { emoji: '🎲', name: 'サイコロ', category: 'エンタメ' },
  { emoji: '🎮', name: 'ゲームコントローラー', category: 'エンタメ' },
  { emoji: '🧩', name: 'パズル', category: 'エンタメ' },
  { emoji: '🎈', name: '風船', category: 'エンタメ' },
  { emoji: '🎁', name: 'プレゼント', category: 'エンタメ' },
  { emoji: '🎆', name: '花火', category: 'エンタメ' },
  // 顔・感情
  { emoji: '😀', name: '笑顔', category: '感情' },
  { emoji: '😢', name: '泣き顔', category: '感情' },
  { emoji: '😠', name: '怒り顔', category: '感情' },
  { emoji: '😲', name: '驚き顔', category: '感情' },
  { emoji: '😉', name: 'ウインク', category: '感情' },
  { emoji: '😍', name: 'ラブ', category: '感情' },
  { emoji: '🤔', name: '考え中', category: '感情' },
  { emoji: '😎', name: 'クール', category: '感情' },
  { emoji: '🤐', name: '口チャック', category: '感情' },
  { emoji: '😤', name: 'ムカッ', category: '感情' },
  { emoji: '🥺', name: 'うるうる', category: '感情' },
  { emoji: '🤣', name: '爆笑', category: '感情' },
  { emoji: '🤬', name: '激怒', category: '感情' },
  { emoji: '😈', name: '悪魔顔', category: '感情' },
  { emoji: '💀', name: 'ガイコツ', category: '感情' },
  { emoji: '💩', name: 'うんち', category: '感情' },
  { emoji: '👽', name: '宇宙人', category: '感情' },
  { emoji: '🤡', name: 'ピエロ', category: '感情' },
];

function emojiKey(emoji) {
  return 'emoji_' + emoji;
}

function getRandomEmojis(count, exclude = []) {
  const excludeSet = new Set(exclude.map(e => e.emoji));
  const pool = EMOJIS.filter(e => !excludeSet.has(e.emoji));
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
