<?php
$EMOJIS_LIST = [
  ['emoji'=>'🐶','name'=>'犬'],['emoji'=>'🐱','name'=>'猫'],['emoji'=>'🐭','name'=>'ネズミ'],
  ['emoji'=>'🐹','name'=>'ハムスター'],['emoji'=>'🐰','name'=>'ウサギ'],['emoji'=>'🦊','name'=>'キツネ'],
  ['emoji'=>'🦝','name'=>'アライグマ'],['emoji'=>'🐻','name'=>'クマ'],['emoji'=>'🐼','name'=>'パンダ'],
  ['emoji'=>'🐨','name'=>'コアラ'],['emoji'=>'🐯','name'=>'トラ'],['emoji'=>'🦁','name'=>'ライオン'],
  ['emoji'=>'🐄','name'=>'ウシ'],['emoji'=>'🐷','name'=>'ブタ'],['emoji'=>'🐑','name'=>'ヒツジ'],
  ['emoji'=>'🐐','name'=>'ヤギ'],['emoji'=>'🐪','name'=>'ラクダ'],['emoji'=>'🦒','name'=>'キリン'],
  ['emoji'=>'🐘','name'=>'ゾウ'],['emoji'=>'🦏','name'=>'サイ'],['emoji'=>'🦛','name'=>'カバ'],
  ['emoji'=>'🐴','name'=>'ウマ'],['emoji'=>'🐒','name'=>'サル'],['emoji'=>'🦍','name'=>'ゴリラ'],
  ['emoji'=>'🐋','name'=>'クジラ'],['emoji'=>'🐬','name'=>'イルカ'],['emoji'=>'🦦','name'=>'カワウソ'],
  ['emoji'=>'🦇','name'=>'コウモリ'],['emoji'=>'🦨','name'=>'スカンク'],['emoji'=>'🦘','name'=>'カンガルー'],
  ['emoji'=>'🐿️','name'=>'リス'],['emoji'=>'🦔','name'=>'ハリネズミ'],
  ['emoji'=>'🐔','name'=>'ニワトリ'],['emoji'=>'🐧','name'=>'ペンギン'],['emoji'=>'🐦','name'=>'青い鳥'],
  ['emoji'=>'🦉','name'=>'フクロウ'],['emoji'=>'🦅','name'=>'ワシ'],['emoji'=>'🦆','name'=>'アヒル'],
  ['emoji'=>'🦩','name'=>'フラミンゴ'],['emoji'=>'🦚','name'=>'クジャク'],['emoji'=>'🦜','name'=>'オウム'],
  ['emoji'=>'🦢','name'=>'白鳥'],['emoji'=>'🦄','name'=>'ユニコーン'],
  ['emoji'=>'🐍','name'=>'ヘビ'],['emoji'=>'🦎','name'=>'トカゲ'],['emoji'=>'🐊','name'=>'ワニ'],
  ['emoji'=>'🐢','name'=>'カメ'],['emoji'=>'🐸','name'=>'カエル'],['emoji'=>'🐉','name'=>'ドラゴン'],
  ['emoji'=>'🐟','name'=>'魚'],['emoji'=>'🐡','name'=>'フグ'],['emoji'=>'🦈','name'=>'サメ'],
  ['emoji'=>'🐙','name'=>'タコ'],['emoji'=>'🦀','name'=>'カニ'],['emoji'=>'🦐','name'=>'エビ'],
  ['emoji'=>'🐌','name'=>'カタツムリ'],
  ['emoji'=>'🦋','name'=>'チョウ'],['emoji'=>'🐛','name'=>'毛虫'],['emoji'=>'🐜','name'=>'アリ'],
  ['emoji'=>'🐝','name'=>'ハチ'],['emoji'=>'🐞','name'=>'テントウムシ'],['emoji'=>'🦗','name'=>'バッタ'],
  ['emoji'=>'🕷️','name'=>'クモ'],['emoji'=>'🦂','name'=>'サソリ'],
  ['emoji'=>'🦕','name'=>'恐竜（長首）'],['emoji'=>'🦖','name'=>'恐竜（肉食）'],
  ['emoji'=>'🌲','name'=>'もみの木'],['emoji'=>'🌳','name'=>'落葉樹'],['emoji'=>'🌴','name'=>'ヤシの木'],
  ['emoji'=>'🌵','name'=>'サボテン'],['emoji'=>'🌾','name'=>'稲穂'],['emoji'=>'🍀','name'=>'四つ葉のクローバー'],
  ['emoji'=>'🍃','name'=>'葉っぱ'],['emoji'=>'🍁','name'=>'落ち葉'],
  ['emoji'=>'🌹','name'=>'バラ'],['emoji'=>'💐','name'=>'花束'],['emoji'=>'🌻','name'=>'ヒマワリ'],
  ['emoji'=>'🌷','name'=>'チューリップ'],['emoji'=>'🌸','name'=>'桜'],['emoji'=>'🌼','name'=>'タンポポ'],
  ['emoji'=>'🍎','name'=>'リンゴ'],['emoji'=>'🍊','name'=>'オレンジ'],['emoji'=>'🍋','name'=>'レモン'],
  ['emoji'=>'🍌','name'=>'バナナ'],['emoji'=>'🍉','name'=>'スイカ'],['emoji'=>'🍇','name'=>'ブドウ'],
  ['emoji'=>'🍓','name'=>'イチゴ'],['emoji'=>'🍈','name'=>'メロン'],['emoji'=>'🍒','name'=>'サクランボ'],
  ['emoji'=>'🍑','name'=>'モモ'],['emoji'=>'🍍','name'=>'パイナップル'],['emoji'=>'🥝','name'=>'キウイ'],
  ['emoji'=>'🍅','name'=>'トマト'],['emoji'=>'🍆','name'=>'ナス'],['emoji'=>'🥦','name'=>'ブロッコリー'],
  ['emoji'=>'🥬','name'=>'レタス'],['emoji'=>'🥒','name'=>'キュウリ'],['emoji'=>'🌽','name'=>'トウモロコシ'],
  ['emoji'=>'🌶️','name'=>'トウガラシ'],['emoji'=>'🥕','name'=>'ニンジン'],['emoji'=>'🧄','name'=>'ニンニク'],
  ['emoji'=>'🧅','name'=>'タマネギ'],['emoji'=>'🥔','name'=>'ジャガイモ'],['emoji'=>'🍠','name'=>'サツマイモ'],
  ['emoji'=>'🌰','name'=>'栗'],['emoji'=>'🍄','name'=>'キノコ'],
  ['emoji'=>'🍞','name'=>'パン'],['emoji'=>'🥞','name'=>'パンケーキ'],
  ['emoji'=>'🍖','name'=>'骨付き肉'],['emoji'=>'🍗','name'=>'チキン'],['emoji'=>'🥓','name'=>'ベーコン'],
  ['emoji'=>'🍔','name'=>'ハンバーガー'],['emoji'=>'🌭','name'=>'ホットドッグ'],['emoji'=>'🍳','name'=>'目玉焼き'],
  ['emoji'=>'🧀','name'=>'チーズ'],['emoji'=>'🥪','name'=>'サンドイッチ'],
  ['emoji'=>'🍙','name'=>'おにぎり'],['emoji'=>'🍱','name'=>'お弁当'],['emoji'=>'🍣','name'=>'寿司'],
  ['emoji'=>'🍜','name'=>'ラーメン'],['emoji'=>'🥟','name'=>'餃子'],['emoji'=>'🍤','name'=>'天ぷら'],
  ['emoji'=>'🍢','name'=>'おでん'],['emoji'=>'🍛','name'=>'カレー'],['emoji'=>'🍚','name'=>'ご飯'],
  ['emoji'=>'🍕','name'=>'ピザ'],['emoji'=>'🥗','name'=>'サラダ'],['emoji'=>'🍟','name'=>'フライドポテト'],
  ['emoji'=>'🍲','name'=>'鍋'],
  ['emoji'=>'🍰','name'=>'ショートケーキ'],['emoji'=>'🍫','name'=>'チョコレート'],['emoji'=>'🍬','name'=>'キャンディ'],
  ['emoji'=>'🍦','name'=>'アイスクリーム'],['emoji'=>'🍩','name'=>'ドーナツ'],['emoji'=>'🍪','name'=>'クッキー'],
  ['emoji'=>'🍯','name'=>'蜂蜜'],
  ['emoji'=>'☕','name'=>'コーヒー'],['emoji'=>'🍵','name'=>'お茶'],['emoji'=>'🍺','name'=>'ビール'],
  ['emoji'=>'🍷','name'=>'ワイン'],['emoji'=>'🧃','name'=>'ジュース'],['emoji'=>'🥛','name'=>'牛乳'],
  ['emoji'=>'✏️','name'=>'鉛筆'],['emoji'=>'✂️','name'=>'はさみ'],['emoji'=>'📏','name'=>'定規'],
  ['emoji'=>'📌','name'=>'画鋲'],['emoji'=>'🔍','name'=>'虫眼鏡'],
  ['emoji'=>'🔨','name'=>'ハンマー'],['emoji'=>'🔧','name'=>'レンチ'],['emoji'=>'⛏️','name'=>'つるはし'],
  ['emoji'=>'🔑','name'=>'鍵'],
  ['emoji'=>'💉','name'=>'注射器'],['emoji'=>'💊','name'=>'薬'],['emoji'=>'🔬','name'=>'顕微鏡'],
  ['emoji'=>'🧪','name'=>'試験管'],
  ['emoji'=>'⚔️','name'=>'剣'],['emoji'=>'🛡️','name'=>'盾'],['emoji'=>'🏹','name'=>'弓矢'],
  ['emoji'=>'🔫','name'=>'銃'],['emoji'=>'💣','name'=>'爆弾'],['emoji'=>'🪓','name'=>'斧'],
  ['emoji'=>'🪃','name'=>'ブーメラン'],
  ['emoji'=>'💡','name'=>'電球'],['emoji'=>'🕯️','name'=>'ろうそく'],
  ['emoji'=>'🎸','name'=>'ギター'],['emoji'=>'🎻','name'=>'バイオリン'],['emoji'=>'🎹','name'=>'ピアノ'],
  ['emoji'=>'🎺','name'=>'トランペット'],['emoji'=>'🥁','name'=>'ドラム'],['emoji'=>'🎤','name'=>'マイク'],
  ['emoji'=>'🎵','name'=>'音符'],['emoji'=>'📻','name'=>'ラジオ'],
  ['emoji'=>'⚽','name'=>'サッカーボール'],['emoji'=>'⚾','name'=>'野球ボール'],['emoji'=>'🏀','name'=>'バスケットボール'],
  ['emoji'=>'🎾','name'=>'テニスラケット'],['emoji'=>'🏐','name'=>'バレーボール'],['emoji'=>'🏉','name'=>'ラグビーボール'],
  ['emoji'=>'🏓','name'=>'卓球'],['emoji'=>'🏸','name'=>'バドミントン'],['emoji'=>'⛳','name'=>'ゴルフ'],
  ['emoji'=>'🥊','name'=>'ボクシンググローブ'],['emoji'=>'🥋','name'=>'柔道着'],['emoji'=>'🎣','name'=>'釣り竿'],
  ['emoji'=>'⛸️','name'=>'スケート靴'],['emoji'=>'🏆','name'=>'トロフィー'],['emoji'=>'🥇','name'=>'金メダル'],
  ['emoji'=>'🏋️','name'=>'重量挙げ'],
  ['emoji'=>'🚗','name'=>'車'],['emoji'=>'🚚','name'=>'トラック'],['emoji'=>'🚲','name'=>'自転車'],
  ['emoji'=>'🏍️','name'=>'バイク'],['emoji'=>'🚃','name'=>'電車'],['emoji'=>'🚅','name'=>'新幹線'],
  ['emoji'=>'🚜','name'=>'トラクター'],
  ['emoji'=>'✈️','name'=>'飛行機'],['emoji'=>'🚀','name'=>'ロケット'],['emoji'=>'🚁','name'=>'ヘリコプター'],
  ['emoji'=>'🛸','name'=>'UFO'],
  ['emoji'=>'🚢','name'=>'船'],['emoji'=>'⚓','name'=>'いかり'],
  ['emoji'=>'⛩️','name'=>'神社'],['emoji'=>'🏯','name'=>'城（日本）'],['emoji'=>'🏠','name'=>'家'],
  ['emoji'=>'🏰','name'=>'城（西洋）'],['emoji'=>'⛪','name'=>'教会'],
  ['emoji'=>'🌋','name'=>'火山'],['emoji'=>'🏜️','name'=>'砂漠'],['emoji'=>'🏖️','name'=>'ビーチ'],
  ['emoji'=>'🏝️','name'=>'島'],['emoji'=>'🌉','name'=>'橋'],['emoji'=>'🏙️','name'=>'都会'],
  ['emoji'=>'👮','name'=>'警察官'],['emoji'=>'🕵️','name'=>'探偵'],['emoji'=>'🤴','name'=>'王子'],
  ['emoji'=>'👸','name'=>'王女'],['emoji'=>'👼','name'=>'天使'],['emoji'=>'🎅','name'=>'サンタ'],
  ['emoji'=>'🧙','name'=>'魔法使い'],['emoji'=>'🧟','name'=>'ゾンビ'],['emoji'=>'🤖','name'=>'ロボット'],
  ['emoji'=>'🧛','name'=>'吸血鬼'],['emoji'=>'🧜','name'=>'人魚'],['emoji'=>'🧚','name'=>'妖精'],
  ['emoji'=>'👑','name'=>'王冠'],['emoji'=>'💪','name'=>'筋肉'],['emoji'=>'🤝','name'=>'握手'],
  ['emoji'=>'🙏','name'=>'祈る手'],
  ['emoji'=>'🇯🇵','name'=>'日本'],['emoji'=>'🇺🇸','name'=>'アメリカ'],['emoji'=>'🇬🇧','name'=>'イギリス'],
  ['emoji'=>'🇫🇷','name'=>'フランス'],['emoji'=>'🇩🇪','name'=>'ドイツ'],['emoji'=>'🇮🇹','name'=>'イタリア'],
  ['emoji'=>'🇪🇸','name'=>'スペイン'],['emoji'=>'🇨🇳','name'=>'中国'],['emoji'=>'🇰🇷','name'=>'韓国'],
  ['emoji'=>'🇷🇺','name'=>'ロシア'],['emoji'=>'🇧🇷','name'=>'ブラジル'],['emoji'=>'🇦🇺','name'=>'オーストラリア'],
  ['emoji'=>'🇨🇦','name'=>'カナダ'],['emoji'=>'🇮🇳','name'=>'インド'],['emoji'=>'🇲🇽','name'=>'メキシコ'],
  ['emoji'=>'🇹🇭','name'=>'タイ'],['emoji'=>'🇬🇷','name'=>'ギリシャ'],['emoji'=>'🇹🇼','name'=>'台湾'],
  ['emoji'=>'☀️','name'=>'晴れ'],['emoji'=>'☁️','name'=>'曇り'],['emoji'=>'❄️','name'=>'雪'],
  ['emoji'=>'⚡','name'=>'雷'],['emoji'=>'🌈','name'=>'虹'],['emoji'=>'🌪️','name'=>'竜巻'],
  ['emoji'=>'🌀','name'=>'台風'],['emoji'=>'⛄','name'=>'雪だるま'],
  ['emoji'=>'🌙','name'=>'三日月'],['emoji'=>'⭐','name'=>'星'],['emoji'=>'🌠','name'=>'流れ星'],
  ['emoji'=>'🌍','name'=>'地球'],['emoji'=>'☄️','name'=>'彗星'],['emoji'=>'🌌','name'=>'銀河'],
  ['emoji'=>'💻','name'=>'パソコン'],['emoji'=>'📱','name'=>'スマホ'],['emoji'=>'📺','name'=>'テレビ'],
  ['emoji'=>'📷','name'=>'カメラ'],['emoji'=>'🔋','name'=>'バッテリー'],
  ['emoji'=>'✉️','name'=>'手紙'],['emoji'=>'📦','name'=>'小包'],['emoji'=>'📚','name'=>'本'],
  ['emoji'=>'📰','name'=>'新聞'],['emoji'=>'🗺️','name'=>'地図'],['emoji'=>'📅','name'=>'カレンダー'],
  ['emoji'=>'💵','name'=>'お札'],['emoji'=>'💎','name'=>'宝石'],['emoji'=>'💍','name'=>'指輪'],
  ['emoji'=>'👛','name'=>'財布'],
  ['emoji'=>'🎩','name'=>'帽子'],['emoji'=>'👓','name'=>'眼鏡'],['emoji'=>'🕶️','name'=>'サングラス'],
  ['emoji'=>'👟','name'=>'靴'],['emoji'=>'👠','name'=>'ハイヒール'],['emoji'=>'☂️','name'=>'傘'],
  ['emoji'=>'⌚','name'=>'時計'],
  ['emoji'=>'🃏','name'=>'トランプ'],['emoji'=>'♟️','name'=>'チェス'],['emoji'=>'🎲','name'=>'サイコロ'],
  ['emoji'=>'🎮','name'=>'ゲームコントローラー'],['emoji'=>'🧩','name'=>'パズル'],['emoji'=>'🎈','name'=>'風船'],
  ['emoji'=>'🎁','name'=>'プレゼント'],['emoji'=>'🎆','name'=>'花火'],
  ['emoji'=>'😀','name'=>'笑顔'],['emoji'=>'😢','name'=>'泣き顔'],['emoji'=>'😠','name'=>'怒り顔'],
  ['emoji'=>'😲','name'=>'驚き顔'],['emoji'=>'😉','name'=>'ウインク'],['emoji'=>'😍','name'=>'ラブ'],
  ['emoji'=>'🤔','name'=>'考え中'],['emoji'=>'😎','name'=>'クール'],['emoji'=>'🤐','name'=>'口チャック'],
  ['emoji'=>'😤','name'=>'ムカッ'],['emoji'=>'🥺','name'=>'うるうる'],['emoji'=>'🤣','name'=>'爆笑'],
  ['emoji'=>'🤬','name'=>'激怒'],['emoji'=>'😈','name'=>'悪魔顔'],['emoji'=>'💀','name'=>'ガイコツ'],
];

function getRandomEmojisPhp(int $count, array $exclude = []): array {
    global $EMOJIS_LIST;
    $available = array_values(array_filter($EMOJIS_LIST, fn($e) => !in_array($e['emoji'], $exclude)));
    shuffle($available);
    return array_slice($available, 0, min($count, count($available)));
}

function generateUUID(): string {
    $data = random_bytes(16);
    $data[6] = chr(ord($data[6]) & 0x0f | 0x40);
    $data[8] = chr(ord($data[8]) & 0x3f | 0x80);
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}

function generateRoomId(): string {
    return strtolower(substr(bin2hex(random_bytes(4)), 0, 8));
}
